#Server port
server:
  port: 8886
#application name
spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#it is a client and a gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka